
(()=>{
 const cfg=window.APP_CONFIG||{}, sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
 const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];
 let me=null, users=[], templates=[], docs=[], assignments=[], lang=localStorage.getItem('fb_ui_lang')||'zh', activeAssignDoc=null;
 const templateLabels={
  receipt_two_companies:['安娜10万收条','Расписка Анны 100 000'],
  receipt_global:['安娜5万收条','Расписка Анны 50 000'],
  consulting_receipt:['阿列克谢4万收条','Расписка Алексея 40 000'],
  application:['申请转团队','Заявление о переводе команды']
 };
 function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 function setLang(v){lang=v;localStorage.setItem('fb_ui_lang',v);document.documentElement.lang=v==='zh'?'zh-CN':'ru';$('#toggleLang').textContent=v==='zh'?'中 / RU':'RU / 中';renderHeader();renderUserHome()}
 function renderHeader(){if(!me)return;const n=lang==='zh'?(me.display_name_zh||me.display_name_ru):(me.display_name_ru||me.display_name_zh);$('#who').textContent=(me.is_admin?(lang==='zh'?'管理员 · ':'Администратор · '):'')+n}
 async function login(e){e.preventDefault();$('#loginError').classList.add('hidden');const code=$('#loginId').value.trim().toLowerCase();const email=`${code}@${cfg.LOGIN_EMAIL_DOMAIN||'example.com'}`;const {error}=await sb.auth.signInWithPassword({email,password:$('#password').value});if(error){$('#loginError').textContent='账号或密码错误 / Неверный ID или пароль';$('#loginError').classList.remove('hidden');return}await boot()}
 $('#loginForm').addEventListener('submit',login);$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};$('#toggleLang').onclick=()=>setLang(lang==='zh'?'ru':'zh');
 async function boot(){const {data:{user}}=await sb.auth.getUser();if(!user){$('#loginView').classList.remove('hidden');$('#appView').classList.add('hidden');return}
  const {data:p,error}=await sb.from('profiles').select('*').eq('id',user.id).single();if(error||!p){$('#loginError').textContent='Profile not found';$('#loginError').classList.remove('hidden');return}
  me=p;$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');renderHeader();await loadUserDocs();if(me.is_admin){$('#adminHome').classList.remove('hidden');await loadAdmin()}}
 async function loadUserDocs(){const {data}=await sb.from('documents').select('id,type,title_ru,title_zh,created_at,source_html').eq('is_active',true).order('created_at',{ascending:false});docs=data||[];renderUserHome()}
 function renderUserHome(){if(!me)return;$('#myDocsTitle').textContent=lang==='zh'?'我的文件':'Мои документы';$('#myDocsHint').textContent=lang==='zh'?'只显示分配给您的文件。':'Показываются только назначенные вам документы.';const host=$('#userDocs');host.innerHTML='';const list=me.is_admin?[]:docs;$('#userHome').classList.toggle('hidden',me.is_admin);$('#userEmpty').classList.toggle('hidden',list.length>0);list.forEach(d=>{const el=document.createElement('article');el.className='doc-card';const title=lang==='zh'?(d.title_zh||d.title_ru):(d.title_ru||d.title_zh);el.innerHTML=`<div class="pill">${esc(d.type)}</div><h3>${esc(title)}</h3><div class="muted">${new Date(d.created_at).toLocaleDateString()}</div><div class="actions"><a href="viewer.html?id=${encodeURIComponent(d.id)}">${lang==='zh'?'打开文件':'Открыть'}</a></div>`;host.appendChild(el)})}
 async function loadAdmin(){
  const [u,t,d,a]=await Promise.all([
   sb.from('profiles').select('*').order('created_at'),
   sb.from('document_templates').select('*').order('template_key'),
   sb.from('documents').select('*').order('created_at',{ascending:false}),
   sb.from('document_assignments').select('*').order('assigned_at',{ascending:false})
  ]);
  users=u.data||[];templates=t.data||[];docs=d.data||[];assignments=a.data||[];renderTemplates();renderAdminDocs();renderUsers();fillDocDialog()
 }
 function renderTemplates(){const h=$('#templateList');h.innerHTML='';templates.forEach(t=>{const names=templateLabels[t.template_key]||[t.title_zh,t.title_ru];const row=document.createElement('div');row.className='template-row';row.innerHTML=`<div><strong>${esc(names[0])}</strong><div class="muted">${esc(names[1])}</div><div class="${t.source_html?'status-ok':'status-missing'}">${t.source_html?'✓ 已导入原源代码':'尚未导入源代码'}</div></div><div><input type="file" accept=".txt,.html,text/plain,text/html" data-template="${esc(t.template_key)}"><button class="primary small" data-save-template="${esc(t.template_key)}">导入/替换</button></div>`;h.appendChild(row)});
  $$('[data-save-template]').forEach(b=>b.onclick=async()=>{const key=b.dataset.saveTemplate,inp=$(`[data-template="${CSS.escape(key)}"]`);if(!inp.files[0])return alert('请选择对应的原源代码文件。');let text=await inp.files[0].text();text=patchIndependentSignatures(key,text);b.disabled=true;b.textContent='保存中…';const {error}=await sb.from('document_templates').update({source_html:text}).eq('template_key',key);if(error)alert(error.message);else alert('已保存。');await loadAdmin()})
 }
 function patchIndependentSignatures(key,src){
  // The uploaded original source remains the base. We only add the agreed behavior:
  // RU and ZH signatures are kept separately when the user switches language.
  if(!src.includes('<!DOCTYPE html') && !src.includes('<!doctype html')) return src;
  if(src.includes('const signatureStore=')) return src;
  if(key!=='application'){
    src=src.replace("const canvas=$('signatureCanvas'),ctx=canvas.getContext('2d');let drawing=false,lastX=0,lastY=0,signatureData=null,confirmed=false,currentImageData=null;",
    "const canvas=$('signatureCanvas'),ctx=canvas.getContext('2d');let drawing=false,lastX=0,lastY=0,signatureData=null,confirmed=false,currentImageData=null;const signatureStore={ru:{data:null,confirmed:false},zh:{data:null,confirmed:false}};function saveLangSignatureState(){signatureStore[currentLang]={data:signatureData,confirmed};}function loadLangSignatureState(){const s=signatureStore[currentLang]||{data:null,confirmed:false};signatureData=s.data;confirmed=s.confirmed;$('confirmSignatureBtn').disabled=!signatureData;$('createImageBtn').disabled=!confirmed;}");
    src=src.replace("signatureData=null;confirmed=false;$('confirmSignatureBtn').disabled=true;$('createImageBtn').disabled=true","signatureData=null;confirmed=false;saveLangSignatureState();$('confirmSignatureBtn').disabled=true;$('createImageBtn').disabled=true");
    src=src.replace("signatureData=await trimSignature(signatureData);confirmed=true;$('createImageBtn').disabled=false","signatureData=await trimSignature(signatureData);confirmed=true;saveLangSignatureState();$('createImageBtn').disabled=false");
    src=src.replace("if($('signatureArea').classList.contains('visible'))setTimeout(()=>{resizeCanvas();","if($('signatureArea').classList.contains('visible'))setTimeout(()=>{loadLangSignatureState();resizeCanvas();");
    src=src.replace("function buildPage(sig=null){","function buildPage(includeSignatures=false){const sigRu=includeSignatures?signatureStore.ru.data:null,sigZh=includeSignatures?signatureStore.zh.data:null;");
    src=src.replaceAll("${sig&&currentLang==='ru'?`<img src=\"${sig}\"","${sigRu?`<img src=\"${sigRu}\"");
    src=src.replaceAll("${sig&&currentLang==='zh'?`<img src=\"${sig}\"","${sigZh?`<img src=\"${sigZh}\"");
    src=src.replace("renderPage(buildPage()).then","renderPage(buildPage(false)).then");
    src=src.replace("const p=buildPage(signatureData)","saveLangSignatureState();const p=buildPage(true)");
    src=src.replace("$('languageSelect').onchange=e=>{currentLang=e.target.value;","$('languageSelect').onchange=e=>{saveLangSignatureState();currentLang=e.target.value;loadLangSignatureState();");
    return src;
  }
  src=src.replace("let signatureConfirmed = false;","let signatureConfirmed = false;\\n        const signatureStore={ru:{data:null,confirmed:false},zh:{data:null,confirmed:false}};\\n        function saveLanguageSignatureState(){signatureStore[currentLang]={data:signatureData,confirmed:signatureConfirmed};}\\n        function loadLanguageSignatureState(){const s=signatureStore[currentLang]||{data:null,confirmed:false};signatureData=s.data;signatureConfirmed=s.confirmed;confirmSignatureBtn.disabled=!signatureData;createImageBtn.disabled=!signatureConfirmed;}");
  src=src.replace("signatureData = null;\\n            signatureConfirmed = false;","signatureData = null;\\n            signatureConfirmed = false;\\n            saveLanguageSignatureState();");
  src=src.replace("signatureConfirmed = true;\\n            createImageBtn.disabled = false;","signatureConfirmed = true;\\n            saveLanguageSignatureState();\\n            createImageBtn.disabled = false;");
  src=src.replace("resizeCanvas();\\n                    signatureArea.scrollIntoView","loadLanguageSignatureState();\\n                    resizeCanvas();\\n                    signatureArea.scrollIntoView");
  src=src.replace("function buildA4DocumentPage(signatureSrc = null) {","function buildA4DocumentPage(includeSignatures = false) {\\n            const signatureRu=includeSignatures?signatureStore.ru.data:null;\\n            const signatureZh=includeSignatures?signatureStore.zh.data:null;");
  src=src.replace("${signatureSrc && currentLang === 'ru' ? `<img class=\"signature-image\" src=\"${signatureSrc}\" alt=\"Подпись\">` : ''}","${signatureRu ? `<img class=\"signature-image\" src=\"${signatureRu}\" alt=\"Подпись\">` : ''}");
  src=src.replace("${signatureSrc && currentLang === 'zh' ? `<img class=\"signature-image\" src=\"${signatureSrc}\" alt=\"签字\">` : ''}","${signatureZh ? `<img class=\"signature-image\" src=\"${signatureZh}\" alt=\"签字\">` : ''}");
  src=src.replace("buildA4DocumentPage(null)","buildA4DocumentPage(false)");
  src=src.replace("const page = buildA4DocumentPage(signatureData);","saveLanguageSignatureState();\\n            const page = buildA4DocumentPage(true);");
  src=src.replace("currentLang = this.value === 'zh' ? 'zh' : 'ru';","saveLanguageSignatureState();\\n            currentLang = this.value === 'zh' ? 'zh' : 'ru';\\n            loadLanguageSignatureState();");
  return src;
 }
 function fillDocDialog(){const s=$('#docTemplate');s.innerHTML=templates.map(t=>`<option value="${esc(t.id)}">${esc(t.title_zh)} / ${esc(t.title_ru)}${t.source_html?'':'（未导入）'}</option>`).join('');renderRecipientList('#recipientList',new Set());}
 function ordinaryUsers(){return users.filter(u=>!u.is_admin)}
 function renderRecipientList(selector,selected){const h=$(selector);h.innerHTML='';ordinaryUsers().forEach(u=>{const label=document.createElement('label');label.className='check-item';label.innerHTML=`<input type="checkbox" value="${esc(u.id)}" ${selected.has(u.id)?'checked':''}><span><strong>${esc(u.display_name_zh||u.display_name_ru)}</strong><br><span class="muted">${esc(u.employee_code)}</span></span>`;h.appendChild(label)})}
 $('#newDocBtn').onclick=()=>{$('#docDialog').showModal()};$('#selectAllUsers').onclick=()=>$$('#recipientList input').forEach(x=>x.checked=true);$('#clearUsers').onclick=()=>$$('#recipientList input').forEach(x=>x.checked=false);
 $('#docTemplate').onchange=()=>{const t=templates.find(x=>x.id===$('#docTemplate').value);if(t){$('#docTitleRu').value=t.title_ru;$('#docTitleZh').value=t.title_zh}};
 $('#docDialog').addEventListener('close',async()=>{});
 $('#createDocConfirm').onclick=async e=>{e.preventDefault();const t=templates.find(x=>x.id===$('#docTemplate').value);if(!t)return;if(!t.source_html)return alert('请先导入这个模板的原源代码。');const recipients=$$('#recipientList input:checked').map(x=>x.value);if(!recipients.length)return alert('请选择至少一个接收账户。');const {data:d,error}=await sb.from('documents').insert({owner_id:me.id,type:t.type,title_ru:$('#docTitleRu').value.trim(),title_zh:$('#docTitleZh').value.trim(),payload:t.payload||{},source_html:t.source_html,is_active:true}).select().single();if(error)return alert(error.message);const rows=recipients.map(uid=>({document_id:d.id,user_id:uid,assigned_by:me.id,is_active:true}));const a=await sb.from('document_assignments').insert(rows);if(a.error)return alert(a.error.message);$('#docDialog').close();await loadAdmin()}
 function assigneesFor(docId){return new Set(assignments.filter(a=>a.document_id===docId&&a.is_active).map(a=>a.user_id))}
 function renderAdminDocs(){const h=$('#adminDocs');h.innerHTML='';docs.forEach(d=>{const who=assigneesFor(d.id),names=[...who].map(id=>users.find(u=>u.id===id)).filter(Boolean).map(u=>u.display_name_zh||u.display_name_ru);const row=document.createElement('div');row.className='admin-doc-row';row.innerHTML=`<div class="row"><div><strong>${esc(d.title_zh||d.title_ru)}</strong><div class="muted">${esc(d.title_ru||'')}</div><div class="muted">已发给 ${who.size} 人${names.length?'：'+esc(names.join('、')):''}</div></div><div class="row"><a class="ghost small" href="viewer.html?id=${encodeURIComponent(d.id)}" target="_blank">查看</a><button class="ghost small" data-assign="${d.id}">发放/收回</button><button class="ghost small" data-copy="${d.id}">复制</button><button class="danger small" data-delete="${d.id}">删除</button></div></div>`;h.appendChild(row)});
  $$('[data-assign]').forEach(b=>b.onclick=()=>openAssignments(b.dataset.assign));
  $$('[data-copy]').forEach(b=>b.onclick=()=>copyDoc(b.dataset.copy));
  $$('[data-delete]').forEach(b=>b.onclick=()=>deleteDoc(b.dataset.delete))
 }
 function openAssignments(id){activeAssignDoc=id;renderRecipientList('#assignRecipientList',assigneesFor(id));$('#assignDialog').showModal()}
 $('#saveAssignments').onclick=async e=>{e.preventDefault();if(!activeAssignDoc)return;const chosen=new Set($$('#assignRecipientList input:checked').map(x=>x.value));const current=assignments.filter(a=>a.document_id===activeAssignDoc);for(const u of ordinaryUsers()){const row=current.find(a=>a.user_id===u.id);if(chosen.has(u.id)){if(row){await sb.from('document_assignments').update({is_active:true,assigned_by:me.id}).eq('id',row.id)}else{await sb.from('document_assignments').insert({document_id:activeAssignDoc,user_id:u.id,assigned_by:me.id,is_active:true})}}else if(row&&row.is_active){await sb.from('document_assignments').update({is_active:false}).eq('id',row.id)}}$('#assignDialog').close();await loadAdmin()}
 async function copyDoc(id){const d=docs.find(x=>x.id===id);if(!d)return;const {data:n,error}=await sb.from('documents').insert({owner_id:me.id,type:d.type,title_ru:d.title_ru+' — копия',title_zh:d.title_zh+' — 副本',payload:d.payload||{},source_html:d.source_html,is_active:true}).select().single();if(error)return alert(error.message);alert('已复制。新文件尚未发放，可点击“发放/收回”选择接收人。');await loadAdmin()}
 async function deleteDoc(id){if(!confirm('确认删除这个文件？所有发放关系也会删除。'))return;const {error}=await sb.from('documents').delete().eq('id',id);if(error)alert(error.message);await loadAdmin()}
 function renderUsers(){const h=$('#userList');h.innerHTML='';users.forEach(u=>{const set=new Set(assignments.filter(a=>a.user_id===u.id&&a.is_active).map(a=>a.document_id));const row=document.createElement('div');row.className='user-row';row.innerHTML=`<div class="row"><div><strong>${esc(u.display_name_zh||u.display_name_ru)}</strong> <span class="pill">${esc(u.employee_code)}</span>${u.is_admin?' <span class="pill">管理员</span>':''}<div class="muted">${esc(u.display_name_ru||'')}${u.display_name_zh&&u.display_name_ru?' / ':''}${esc(u.display_name_zh||'')}</div><div class="muted">文件：${set.size}</div></div><div class="row">${u.id===me.id?'':'<button class="ghost small" data-edit-user="'+u.id+'">管理</button>'}</div></div>`;h.appendChild(row)});$$('[data-edit-user]').forEach(b=>b.onclick=()=>openUserEditor(b.dataset.editUser))}
 async function adminUserAction(body){const {data,error}=await sb.functions.invoke('admin-user-management',{body});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
 function friendlyUserError(err){const m=String(err?.message||err||'');const map={INVALID_EMPLOYEE_CODE:'个人编号只能使用英文字母、数字、点、下划线或短横线，长度 2–40 位。',PASSWORD_TOO_SHORT:'密码至少需要 8 位。',NAME_REQUIRED:'俄文姓名或中文姓名至少填写一个。',EMPLOYEE_CODE_EXISTS:'这个个人编号已经存在。',CANNOT_DELETE_SELF:'不能删除当前正在登录的管理员账户。'};return map[m]||m}
 $('#newUserBtn').onclick=()=>{$('#newEmployeeCode').value='';$('#newNameRu').value='';$('#newNameZh').value='';$('#newPassword').value='';$('#userCreateError').classList.add('hidden');$('#userDialog').showModal()};
 $('#createUserConfirm').onclick=async e=>{e.preventDefault();const code=$('#newEmployeeCode').value.trim().toUpperCase(),nameRu=$('#newNameRu').value.trim(),nameZh=$('#newNameZh').value.trim(),password=$('#newPassword').value;$('#userCreateError').classList.add('hidden');if(!code||!password||(!nameRu&&!nameZh)){const el=$('#userCreateError');el.textContent='请填写个人编号、密码，以及至少一种语言的姓名。';el.classList.remove('hidden');return}try{$('#createUserConfirm').disabled=true;$('#createUserConfirm').textContent='创建中…';await adminUserAction({action:'create',employee_code:code,display_name_ru:nameRu,display_name_zh:nameZh,password});$('#userDialog').close();await loadAdmin();alert('账户已创建。')}catch(err){const el=$('#userCreateError');el.textContent=friendlyUserError(err);el.classList.remove('hidden')}finally{$('#createUserConfirm').disabled=false;$('#createUserConfirm').textContent='创建账户'}};
 function openUserEditor(id){const u=users.find(x=>x.id===id);if(!u)return;$('#editUserId').value=u.id;$('#editUserCode').textContent=`个人编号：${u.employee_code}`;$('#editNameRu').value=u.display_name_ru||'';$('#editNameZh').value=u.display_name_zh||'';$('#resetPassword').value='';$('#editUserDialog').showModal()}
 $('#saveUserProfile').onclick=async()=>{const id=$('#editUserId').value;try{$('#saveUserProfile').disabled=true;await adminUserAction({action:'update_profile',user_id:id,display_name_ru:$('#editNameRu').value,display_name_zh:$('#editNameZh').value});await loadAdmin();alert('姓名已保存。')}catch(err){alert(friendlyUserError(err))}finally{$('#saveUserProfile').disabled=false}};
 $('#resetPasswordBtn').onclick=async()=>{const id=$('#editUserId').value,p=$('#resetPassword').value;if(p.length<8)return alert('新密码至少 8 位。');if(!confirm('确认重置这个账户的密码？'))return;try{$('#resetPasswordBtn').disabled=true;await adminUserAction({action:'update_password',user_id:id,password:p});$('#resetPassword').value='';alert('密码已重置。')}catch(err){alert(friendlyUserError(err))}finally{$('#resetPasswordBtn').disabled=false}};
 $('#deleteUserBtn').onclick=async()=>{const id=$('#editUserId').value,u=users.find(x=>x.id===id);if(!u)return;if(!confirm(`确认删除账户 ${u.employee_code}？该账户将无法再登录，发放给他的文件关系也会同时删除。`))return;try{$('#deleteUserBtn').disabled=true;await adminUserAction({action:'delete',user_id:id});$('#editUserDialog').close();await loadAdmin();alert('账户已删除。')}catch(err){alert(friendlyUserError(err))}finally{$('#deleteUserBtn').disabled=false}};
 $$('.admin-tabs button').forEach(b=>b.onclick=()=>{$$('.admin-tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.admin-tab').forEach(x=>x.classList.add('hidden'));$('#tab-'+b.dataset.tab).classList.remove('hidden')});
 sb.auth.onAuthStateChange((ev)=>{if(ev==='SIGNED_OUT')location.reload()});
 setLang(lang);boot();
})();
